### ISSUE TITLE
Ai is seemingly always on "seek"

### ISSUE THREAD

**Issue by justanormalplayer** [leveleditor/CAMM-Crystal-Alien-Map-Maker#7]
as the title implies, it doesnt matter what i set the enemy unit ai to they still move like they are on the seek function

**Comment by Landlighter** [comment]
I think I figured out a couple parts of this. Each unit has a place in its UI called "Monolithic property of things" and this seems to change up the behavior somewhat.
For example,
If you set the AI to "still" and add a number it will stay still for that amount of time (1 second is roughly 20 in the monolithic property box)
If you set the AI to "roam" and add a number that will be the range of its movement (inputting two will give it a movement range of two tiles in any direction)
I haven't figured out what to do for "seek" or "guard"

**Comment by leveleditor** [comment]
This is mainly an issue with needing to clarify in the editor what the AI modes and the "monolithic property of things" actually are: how they are related, adding proper options to choose from, and better wording and explanation of what each option actually does.

I'm now tracking this and the related details on issue #11, imported from my old todo list.
