### ISSUE TITLE
Miscellaneous #2

### ISSUE THREAD

**Issue by Landlighter** [leveleditor/CAMM-Crystal-Alien-Map-Maker#9]
So I've been messing around with the level for awhile now (and due to the coronavirus I'll be home for three weeks with nothing to do) and I've put together a list of things that would be really good to add
Note: Some of this overlaps with my first post
- Music should have all the tracks, but could prove to be very difficult to implement because CAMM does this bizarrely
- The AI modes "seek" and "guard" I can't figure out how to work. There's likely something that you type in the "monothilic property of things" box but I'm not sure what 
- The AI modes "still" and "roam" have a combination with numbers. 
         - In "still" if you input a number in the "monothilic property of things" it will remain still for 
            that amount of time (20 = 1 second)
         - In "roam" if you input a number in the "monothilic property of things" it will allow that unit 
            to move that number of tiles (if you put in 2, it will roam a maximum of 2 tiles in any 
           direction)
- There should be a way to "limit" the build chain. For example, in some levels, they don't let you build past a certain structure/unit.  I think a possible way of implementing this could be in the map settings, because it would never change in the middle of a level

Ex: In Astro level 3 you can't build past defense stations.
![Astro lvl 3 build limit](https://user-images.githubusercontent.com/51828285/76707371-095e8000-66c5-11ea-9d88-347d7fcacd56.png)

- There should be a way to have certain areas of fog be visible without one of your own units there

Ex: In the Astros' Conflict Mode it shows you the alien mothership through the fog even though you don't have a unit there
![Conflict Mode - Astros - Special Fog](https://user-images.githubusercontent.com/51828285/76707324-876e5700-66c4-11ea-804d-7f7a9d7fb639.png)

- Screen jumps/starting screen: this was mentioned before and just adds a nice aesthetic to the game. (If you go to conflict mode, you'll see why the screen jumps can be really useful)

Ex: In Astro Level 4 the screen starts on the trike, where in CAMM the level starts at the base, because it defaults to the home base.
![Astro Lvl 4 screen](https://user-images.githubusercontent.com/51828285/76707394-4b87c180-66c5-11ea-83cc-9623fd700c55.png)

Also shown in the last screen shot are the "indicators" (AKA the "teach you how to play the game arrows") which are another really small thing that could improve the game

The last and probably most important issue: special win/lose conditions. I know this is probably pretty hard to implement, but certain levels have special condtions to beat them or certain conditions that if met will cause you to lose. 
For example, 
- Astro Level 1 requires you to get credits to win. 
- Astro Level 9 requires you to capture the Experiment Lab to win.
- Alien Level 5 causes you to lose if you lose the speeder. 
- Astro Special Ops 1 requires you build a driller to win. 
- Astro Special Ops 2 causes you to lose if the driller is destroyed.
- Astro Bonus 3 requires you to build 4 Satellite Uplinks to win.
I think these win conditions would be a very good addition, but I have no idea if they are even possible.

One last thing: I have constructed harder versions of all 10 Astro levels. They're posted later in this thread
Thanks for making CAMM; there is no greater LEGO web game in my opinion!

**Comment by Brian151** [comment]
the main problem is CAC's code, itself

the AI modes are indeed weird to use, and iirc, 'guard' isn't actually implemented properly
tech tree is controlled by some hard-coded if statements
special win/lose conditions are also run through some hard-coded if statements
screen-jumping is done by overriding the camera object's focus to be a specific unit or building
ex:
```actionscript
this.buildings.push(a = new Building(this, "BA_evil", 25, 12));
this.indicators.push(new Indicator(this, a, null, null, "focus"));
			this.indicators.push(new Indicator(this, null, null, dialogue("int_level10_ind1"), "message", 80));
			this.indicators.push(new Indicator(this, b, null, null, "focus"));
			this.indicators.push(new Indicator(this, null, null, dialogue("int_level10_ind2"), "message", 80));
			this.indicators.push(new Indicator(this, c, null, null, "focus"));
			this.indicators.push(new Indicator(this, null, null, dialogue("int_level10_ind3"), "message", 80));```

fog is relatively easy, there's a command/function to clear areas of it.

really, most of these issues come-down to CAC using entirely too many hard-coded hacks, so there are a few steps:
1. devise a format for tools to export
2. write importers
3. mod the functionality in via the wrapper [currently...]

that third step doesn't always go so smoothly. the flash wrapper is asking actionscript to do some things it really isn't meant to do. there have been some undesirable side effects implementing certain mods.

**Comment by Landlighter** [comment]
I don't know code that well, so sorry I can't help

**Comment by Brian151** [comment]
oh, it's quite alright
i don't expect necessarily that you'd understand the code, just that it exists, and CAC depends heavily on it. 

most games have file formats and special data structures for this stuff. CAC was developed with the intention of being a throw-away adver-game. [ofc, back when adver-games were actually fun] the only real concern was achieve a marketing goal and having something that "works". and it does work... until you try making it behave like your typical console/pc game. here's where you encounter glitches and realize custom content was never really a priority. 

so, that leaves the redux team with trying to monkey-patch the swf's code [again, doesn't always work well], and devise file/data formats on the spot. we're also trying to do this properly, and not half-ass a solution that needs to be fixed later. for example, we realized at some point that using JSON was better than INI for the map files. ofc, one of the problems with supporting JSON in CAC via the wrapper was finding an AS2-compatible implementation. we failed multiple times. JSON support in flash is LARGELY constrained to AS3. My unit/building editors also currently only support exports of actionscript code and INI configs. relatively easy fix, though. aside from my javascript code that actually makes them work /:

we're used to having limited human resources to work on this project, so no need to apologize for that. what we don't like is people who come and DEMAND things, and believe me, that HAS happened a couple of times.

**Comment by Landlighter** [comment]
Well I'm really happy you guys are working on it regardless of what happens because this game is just the best. Small update: I've actually gotten harder versions of Astros 1-10 and Aliens 1-6. And believe me, my Conflict Mode is a BEAST if you don't plan ahead. Sadly, I'm not quite sure how to attach the files. I might try and put them on a website and link it here maybe.
I also do know someone who is good at coding who could help you guys out. I'll try and contact them soon

**Comment by Landlighter** [comment]
Well I'm really happy you guys are working on it regardless of what happens because this game is just the best. Small update: I've actually gotten harder versions of Astros 1-10 and Aliens 1-7. And believe me, my Conflict Mode is a BEAST if you don't plan ahead.
I also do know someone who is good at coding who could help you guys out. I'll try and contact them soon

**Comment by Landlighter** [comment]
I can't help but notice that CAC doesn't like fullscreen. Is this a bug or is it not possible with the code? On Crystalien Redux, you guys fixed the fullscreen problem, but the CAC Player doesn't seem to be able to go fullscreen. Just curious

**Comment by Landlighter** [comment]
[Hard Mode.zip](https://github.com/leveleditor/CAMM-Crystal-Alien-Map-Maker/files/4554595/Hard.Mode.zip)
Here is all 10 levels for Astros and Aliens Hard Mode!
And here's the guide:
[My Level Guide.docx](https://github.com/leveleditor/CAMM-Crystal-Alien-Map-Maker/files/4554640/My.Level.Guide.docx)

**Comment by Brian151** [comment]
While we appreciate people actually taking interest in making maps with CAMM, the github issues are not the place to be submitting or advertising the maps you create. The one exception is when a bug is actually encountered so we [or rather, Josh, as I do not program for CAMM but offer other assistance] can attempt to re-produce it and crush it.

All that said, we are now looking into some means of sharing maps since there seems to be interest in this. No ETA, as even with Covid disrupting things, our daily lifes are still decently busy. So, let's just go with "SOON! ™️"

Additionally, the intended function of the issue tracker is to report individual issues and not batch several of them together. It should best be avoided when at all possible. Now, if a redundancy were to be created by doing this [such as uploading the exact same file], or issues seem to be related in some way, then it would be ok.

Also, before reporting an issue, you might wish to check the following:
1. does a similar issue, open or closed, already exist?
2. are you using the most recent version?
3. is the issue otherwise documented within this repo?
4. is this issue documented somewhere on the todo within our wiki?

**Comment by leveleditor** [comment]
Although this issue has been closed, I'd like to address some of the points here for reference (the same as your previous issue #6).

> Music should have all the tracks, but could prove to be very difficult to implement because CAMM does this bizarrely

Adding the built-in music/audio track selection actually won't be too hard for me to add.
Tracking on issue #13 

> The AI modes "seek" and "guard" I can't figure out how to work. There's likely something that you type in the "monothilic property of things" box but I'm not sure what[...]

Indeed the field "monolithic property of things" (as I "temporarily" named it back then) has been quite hard to understand, so I'll be working on improving that.
Tracking on issue #11 

> There should be a way to "limit" the build chain. For example, in some levels, they don't let you build past a certain structure/unit. I think a possible way of implementing this could be in the map settings, because it would never change in the middle of a level[...]

Tracking on issue #21 

> There should be a way to have certain areas of fog be visible without one of your own units there [...]

For the fog (also known as "shroud"), I do plan to add the ability to manually clear it on any part of the map regardless of where units/buildings are.
Tracking on issue #22 

> Screen jumps/starting screen: this was mentioned before and just adds a nice aesthetic to the game. (If you go to conflict mode, you'll see why the screen jumps can be really useful) [...]

I do want to add this, at least the basic for now to focus the screen/camera when the level starts, and in the future adding more advanced camera focusing via the indicator system.
Tracking on issue #20 and the future advanced features on issue #25 

> Also shown in the last screen shot are the "indicators" (AKA the "teach you how to play the game arrows") which are another really small thing that could improve the game

The indicator system is inter-related with the dialogue and camera focusing. It's quite the can of worms. I'm not sure how far I'll get with this stuff to be honest.
Tracking on issue #25 

> The last and probably most important issue: special win/lose conditions. I know this is probably pretty hard to implement, but certain levels have special condtions to beat them or certain conditions that if met will cause you to lose.

These win/lose conditions are certainly possible to add, but do need some work to add into the UI and the Flash wrapper/map loader mod.
Tracking on issue #19 

> One last thing: I have constructed harder versions of all 10 Astro levels. They're posted later in this thread
> Thanks for making CAMM; there is no greater LEGO web game in my opinion!

Thanks for sharing your input. Hopefully we'll have a better place to post and share your levels in the future, as they will likely just get lost on here.

> I also do know someone who is good at coding who could help you guys out. I'll try and contact them soon

We could always use some help if they're up for it. Pull requests are always welcome and will be reviewed when posted. However I'm not sure that many people would know coding for VB.NET (for CAMM) or ActionScript 2/3 (for the Flash wrapper modding/game side of things) these days.

> I can't help but notice that CAC doesn't like fullscreen. Is this a bug or is it not possible with the code? On Crystalien Redux, you guys fixed the fullscreen problem, but the CAC Player doesn't seem to be able to go fullscreen. Just curious

Actually I totally forgot about that. The Flash wrapper/modding side of things already supported fullscreen from the work that was done to enable it on the website, so really I just needed to spend a bit of time to add it to the CAC Player AIR app as well. This is now done and included in the latest release of the CAC Player app. Make sure to check the updated versions posted to the website.

**Comment by Landlighter** [comment]
Thanks for being awesome! I closed this issue because I saw you open a bunch of stuff related to it, so it was no longer needed
